services:
  mongo:
    image: mongo:latest
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/secrets/mongo-keyfile"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "mongo_data:/data/db"
      - "./mongo-keyfile:/etc/secrets/mongo-keyfile:ro"
    healthcheck:
      test: ["CMD-SHELL", "echo 'rs.status()' | mongosh --port 27017 --username root --password example --quiet || echo 'rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"localhost:27017\" }]})' | mongosh --port 27017 --username root --password example --quiet"]
      interval: 5s
      timeout: 30s
      retries: 5

volumes:
  mongo_data:

