const playgroundData = [
  {
    name: "Central Park Playground",
    type: "EQUIPMENT",
    address: "59th to 110th Street",
    location: "40.785091, -73.968285",
    description: "A large playground with swings and slides.",
    contactPerson: "John Doe",
  },
  {
    name: "Riverside Sports Field",
    type: "SPORT",
    address: "Riverside Dr & W 72nd St",
    location: "40.783060, -73.971249",
    description: "Open field for soccer and baseball.",
    contactPerson: "Jane Smith",
  },
  {
    name: "Lincoln Park Play Area",
    type: "EQUIPMENT",
    address: "2045 N Lincoln Park W",
    location: "41.921438, -87.633773",
    description: "Children's play area with sandbox.",
    contactPerson: "Alex Johnson",
  },
  {
    name: "Beachfront Volleyball Court",
    type: "SPORT",
    address: "Ocean Front Walk",
    location: "34.009242, -118.497604",
    description: "Sandy volleyball courts by the beach.",
    contactPerson: "Maria Garcia",
  },
  {
    name: "Woodland Adventure Playground",
    type: "EQUIPMENT",
    address: "789 Forest Trail",
    location: "37.774929, -122.419416",
    description: "Adventure playground with ropes and climbing.",
    contactPerson: "Robert Martinez",
  },
  {
    name: "City Center Basketball Court",
    type: "SPORT",
    address: "101 City Plaza",
    location: "34.052235, -118.243683",
    description: "Public basketball courts.",
    contactPerson: "Linda Rodriguez",
  },
  {
    name: "Meadowbrook Skate Park",
    type: "EQUIPMENT",
    address: "456 Meadowbrook Lane",
    location: "40.712776, -74.005974",
    description: "Skate park with ramps and rails.",
    contactPerson: "David Lee",
  },
  {
    name: "Sunset Tennis Courts",
    type: "SPORT",
    address: "789 Sunset Blvd",
    location: "34.052235, -118.243683",
    description: "Outdoor tennis courts.",
    contactPerson: "Barbara Wilson",
  },
  {
    name: "Riverbank Climbing Wall",
    type: "EQUIPMENT",
    address: "123 Riverbank Road",
    location: "41.878113, -87.629799",
    description: "Outdoor climbing wall by the river.",
    contactPerson: "Christopher Anderson",
  },
  {
    name: "Hilltop Football Field",
    type: "SPORT",
    address: "321 Hilltop Avenue",
    location: "34.052235, -118.243683",
    description: "Football field with bleachers.",
    contactPerson: "Patricia Thomas",
  },
];

module.exports = { playgroundData };
